"""
DDL / DML rewrite rules: Snowflake → Databricks.
Ensures USING DELTA on all tables, correct identity syntax, etc.
"""
from __future__ import annotations

import re
from .rule_engine import Rule

FLAGS = re.IGNORECASE | re.MULTILINE | re.DOTALL


DDL_RULES: list[Rule] = [

    # =========================================================
    # TABLE DDL
    # =========================================================

    # TRANSIENT → plain Delta table (remove TRANSIENT keyword)
    Rule(
        name="TRANSIENT_TABLE",
        pattern=re.compile(
            r'\bCREATE\s+(OR\s+REPLACE\s+)?TRANSIENT\s+TABLE\b',
            FLAGS,
        ),
        replacement=r'CREATE \1TABLE',
        confidence="high",
        note="TRANSIENT has no Delta equivalent — keyword removed; add short retention property",
    ),

    # TEMPORARY TABLE → TEMPORARY VIEW
    Rule(
        name="TEMPORARY_TABLE",
        pattern=re.compile(
            r'\bCREATE\s+(OR\s+REPLACE\s+)?TEMPORARY\s+TABLE\b',
            FLAGS,
        ),
        replacement=r'CREATE \1TEMPORARY VIEW',
        confidence="medium",
        note="TEMPORARY TABLE → TEMPORARY VIEW in Databricks",
    ),

    # CLONE → SHALLOW CLONE
    Rule(
        name="CLONE_TABLE",
        pattern=re.compile(r'\bCLONE\s+', FLAGS),
        replacement='SHALLOW CLONE ',
        confidence="high",
        note="Snowflake CLONE → Databricks SHALLOW CLONE (Delta)",
    ),

    # AUTOINCREMENT → GENERATED ALWAYS AS IDENTITY (BIGINT required)
    Rule(
        name="AUTOINCREMENT",
        pattern=re.compile(r'\bAUTOINCREMENT\b', FLAGS),
        replacement='GENERATED ALWAYS AS IDENTITY',
        confidence="high",
        note="Column type must be BIGINT for IDENTITY in Databricks",
    ),

    # IDENTITY(start, step) → GENERATED ALWAYS AS IDENTITY (START WITH … INCREMENT BY …)
    Rule(
        name="IDENTITY_with_params",
        pattern=re.compile(r'\bIDENTITY\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)', FLAGS),
        replacement=r'GENERATED ALWAYS AS IDENTITY (START WITH \1 INCREMENT BY \2)',
        confidence="high",
    ),

    # DEFAULT seq.NEXTVAL → GENERATED BY DEFAULT AS IDENTITY
    Rule(
        name="NEXTVAL_default",
        pattern=re.compile(r'\bDEFAULT\s+\w+\.NEXTVAL\b', FLAGS),
        replacement='GENERATED BY DEFAULT AS IDENTITY',
        confidence="medium",
        note="Sequence NEXTVAL replaced with IDENTITY column",
    ),

    # DATA_RETENTION_TIME_IN_DAYS → Delta table property
    Rule(
        name="DATA_RETENTION_DAYS",
        pattern=re.compile(r'\bDATA_RETENTION_TIME_IN_DAYS\s*=\s*(\d+)', FLAGS),
        replacement=lambda m: (
            f"/* DATA_RETENTION converted to TBLPROPERTIES: "
            f"'delta.deletedFileRetentionDuration'='interval {m.group(1)} days' */"
        ),
        confidence="high",
        note="Add to TBLPROPERTIES block",
    ),

    # COMMENT = '...' → COMMENT '...' (remove = sign)
    Rule(
        name="COMMENT_equals",
        pattern=re.compile(r'\bCOMMENT\s*=\s*(\'[^\']*\'|"[^"]*")', FLAGS),
        replacement=r'COMMENT \1',
        confidence="high",
    ),

    # COPY GRANTS → remove (not applicable)
    Rule(
        name="COPY_GRANTS",
        pattern=re.compile(r'\bCOPY\s+GRANTS\b', FLAGS),
        replacement='/* COPY_GRANTS_REMOVED: not applicable in Databricks */',
        confidence="high",
    ),

    # TAG (...) → remove
    Rule(
        name="TAG_clause",
        pattern=re.compile(r'\bWITH\s+TAG\s*\([^)]+\)', FLAGS),
        replacement='/* TAG_REMOVED: use Unity Catalog tags instead */',
        confidence="high",
    ),

    # SEARCH OPTIMIZATION → OPTIMIZE comment
    Rule(
        name="SEARCH_OPTIMIZATION",
        pattern=re.compile(r'\bADD\s+SEARCH\s+OPTIMIZATION\b', FLAGS),
        replacement='/* MANUAL_REVIEW: Run OPTIMIZE <table> ZORDER BY (<high_cardinality_col>) */',
        confidence="high",
    ),

    # WAREHOUSE_SIZE / other Snowflake-only table options → remove
    Rule(
        name="WAREHOUSE_SIZE",
        pattern=re.compile(r'\bWAREHOUSE_SIZE\s*=\s*\S+', FLAGS),
        replacement='/* WAREHOUSE_SIZE_REMOVED */',
        confidence="high",
    ),

    # =========================================================
    # VIEW DDL
    # =========================================================

    # SECURE VIEW → plain VIEW
    Rule(
        name="SECURE_VIEW",
        pattern=re.compile(r'\bCREATE\s+(OR\s+REPLACE\s+)?SECURE\s+VIEW\b', FLAGS),
        replacement=r'CREATE \1VIEW',
        confidence="high",
        note="SECURE VIEW has no equivalent — use Unity Catalog row-level security",
    ),

    # =========================================================
    # STREAM → Change Data Feed
    # =========================================================
    Rule(
        name="CREATE_STREAM",
        pattern=re.compile(
            r'\bCREATE\s+(?:OR\s+REPLACE\s+)?STREAM\s+(\w+)\s+ON\s+TABLE\s+(\S+)',
            FLAGS,
        ),
        replacement=(
            r"/* STREAM_CONVERTED: ALTER TABLE \2 SET TBLPROPERTIES "
            r"('delta.enableChangeDataFeed' = 'true');\n"
            r"-- Read changes: SELECT * FROM table_changes('\2', 1) */"
        ),
        confidence="medium",
        note="Snowflake STREAM → Delta Change Data Feed (CDF)",
    ),

    # =========================================================
    # TASK / PIPE / STAGE → warnings
    # =========================================================
    Rule(
        name="CREATE_TASK",
        pattern=re.compile(r'\bCREATE\s+(?:OR\s+REPLACE\s+)?TASK\b', FLAGS),
        replacement='/* MANUAL_REVIEW: CREATE TASK → Convert to Databricks Workflow */',
        confidence="high",
    ),
    Rule(
        name="CREATE_PIPE",
        pattern=re.compile(r'\bCREATE\s+(?:OR\s+REPLACE\s+)?PIPE\b', FLAGS),
        replacement='/* MANUAL_REVIEW: CREATE PIPE → Convert to Databricks Auto Loader */',
        confidence="high",
    ),
    Rule(
        name="CREATE_STAGE",
        pattern=re.compile(r'\bCREATE\s+(?:OR\s+REPLACE\s+)?(?:EXTERNAL\s+)?STAGE\b', FLAGS),
        replacement='/* MANUAL_REVIEW: CREATE STAGE → Map to external location (DBFS/S3/ADLS) */',
        confidence="high",
    ),
    Rule(
        name="CREATE_FILE_FORMAT",
        pattern=re.compile(r'\bCREATE\s+(?:OR\s+REPLACE\s+)?FILE\s+FORMAT\b', FLAGS),
        replacement='/* MANUAL_REVIEW: FILE FORMAT → specify inline in COPY INTO FORMAT_OPTIONS */',
        confidence="high",
    ),

    # =========================================================
    # COPY INTO
    # =========================================================
    Rule(
        name="COPY_INTO_FROM_STAGE",
        pattern=re.compile(r'COPY\s+INTO\s+(\S+)\s+FROM\s+@(\S+)', FLAGS),
        replacement=(
            r"COPY INTO \1 FROM 'dbfs:/\2'"
            r"  /* MANUAL_REVIEW: update path, FILEFORMAT, FORMAT_OPTIONS, COPY_OPTIONS */"
        ),
        confidence="low",
        note="COPY INTO stage reference → cloud path; update format options manually",
    ),

    # =========================================================
    # DML
    # =========================================================
    Rule(
        name="INSERT_OVERWRITE_INTO",
        pattern=re.compile(r'\bINSERT\s+OVERWRITE\s+INTO\b', FLAGS),
        replacement='INSERT OVERWRITE',
        confidence="high",
    ),

    # SELECT * EXCLUDE (col) → comment
    Rule(
        name="SELECT_EXCLUDE",
        pattern=re.compile(r'\bSELECT\s+\*\s+EXCLUDE\s*\([^)]+\)', FLAGS),
        replacement='SELECT * /* MANUAL_REVIEW: EXCLUDE not supported — list columns explicitly */',
        confidence="low",
    ),

    # SELECT * RENAME → comment
    Rule(
        name="SELECT_RENAME",
        pattern=re.compile(r'\bSELECT\s+\*\s+RENAME\s*\([^)]+\)', FLAGS),
        replacement='SELECT * /* MANUAL_REVIEW: RENAME not supported — list columns explicitly */',
        confidence="low",
    ),

    # SELECT * REPLACE → comment
    Rule(
        name="SELECT_REPLACE",
        pattern=re.compile(r'\bSELECT\s+\*\s+REPLACE\s*\([^)]+\)', FLAGS),
        replacement='SELECT * /* MANUAL_REVIEW: REPLACE not supported — list columns explicitly */',
        confidence="low",
    ),

    # =========================================================
    # SEQUENCE DDL  (Databricks 13.0+ supports sequences)
    # =========================================================
    Rule(
        name="SEQUENCE_DDL",
        pattern=re.compile(
            r'\bCREATE\s+(?:OR\s+REPLACE\s+)?SEQUENCE\s+(\S+)'
            r'(?:\s+START\s+(?:WITH\s+)?(\d+))?'
            r'(?:\s+INCREMENT\s+(?:BY\s+)?(\d+))?',
            FLAGS,
        ),
        replacement=lambda m: (
            f"CREATE SEQUENCE IF NOT EXISTS {m.group(1)}"
            + (f" START WITH {m.group(2)}" if m.group(2) else " START WITH 1")
            + (f" INCREMENT BY {m.group(3)}" if m.group(3) else " INCREMENT BY 1")
            + "  /* Requires Databricks Runtime 13.0+ */"
        ),
        confidence="medium",
        note="Sequences supported in Databricks 13.0+",
    ),
]
