-- =====================================================
-- COMPLETE WORKING SNOWFLAKE SCRIPT (ERROR FREE)
-- =====================================================
-- USE WAREHOUSE COMPUTE_WH;  -- (Databricks: select compute via cluster/SQL warehouse at connection level)

CREATE CATALOG IF NOT EXISTS FRAUD_DETECTION;

CREATE SCHEMA IF NOT EXISTS FRAUD_DETECTION.FRAUD;

-- =====================================================
-- PART 1: CREATE TABLES
-- =====================================================
CREATE OR REPLACE TABLE FRAUD_DETECTION.FRAUD.CUSTOMER_MASTER (
    CUSTOMER_SK BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    CUSTOMER_NAME VARCHAR(200),
    TAX_ID VARCHAR(20),
    EMAIL VARCHAR(200),
    PHONE VARCHAR(20),
    RISK_SCORE DECIMAL(5, 2),
    SEGMENT VARCHAR(50),
    ADDRESS_LINE1 VARCHAR(200),
    ADDRESS_LINE2 VARCHAR(200),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    VALID_FROM TIMESTAMP_NTZ ,
    VALID_TO TIMESTAMP_NTZ ,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP_NTZ ,
    MODIFIED_DATE TIMESTAMP_NTZ ,
    PRIMARY KEY (CUSTOMER_SK)
)
USING DELTA
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.feature.allowColumnDefaults' = 'supported',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact'   = 'true'
);

CREATE OR REPLACE TABLE FRAUD_DETECTION.FRAUD.ACCOUNT_MASTER (
    ACCOUNT_SK BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ACCOUNT_NUMBER VARCHAR(50) NOT NULL,
    CUSTOMER_SK BIGINT NOT NULL,
    ACCOUNT_TYPE VARCHAR(50),
    CURRENCY_CODE CHAR(3),
    OPEN_DATE DATE,
    CLOSE_DATE DATE,
    ACCOUNT_STATUS VARCHAR(20),
    CURRENT_BALANCE DECIMAL(18, 2),
    AVAILABLE_BALANCE DECIMAL(18, 2),
    OVERDRAFT_LIMIT DECIMAL(18, 2),
    INTEREST_RATE DECIMAL(5, 2),
    CREATED_DATE TIMESTAMP_NTZ ,
    MODIFIED_DATE TIMESTAMP_NTZ ,
    PRIMARY KEY (ACCOUNT_SK)
)
USING DELTA
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact'   = 'true'
);

CREATE OR REPLACE TABLE FRAUD_DETECTION.FRAUD.MERCHANT_MASTER (
    MERCHANT_SK BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    MERCHANT_ID VARCHAR(50) NOT NULL,
    MERCHANT_NAME VARCHAR(200),
    CATEGORY_CODE VARCHAR(10),
    RISK_LEVEL VARCHAR(20),
    COUNTRY VARCHAR(50),
    VERIFICATION_STATUS VARCHAR(20) DEFAULT 'VERIFIED',
    CREATED_DATE TIMESTAMP_NTZ ,
    PRIMARY KEY (MERCHANT_SK)
)
USING DELTA
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.feature.allowColumnDefaults' = 'supported',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact'   = 'true'
);

CREATE OR REPLACE TABLE FRAUD_DETECTION.FRAUD.TRANSACTION_FACT (
    TRANSACTION_SK BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    TRANSACTION_ID VARCHAR(50) NOT NULL,
    ACCOUNT_SK BIGINT NOT NULL,
    MERCHANT_SK BIGINT NOT NULL,
    TRANSACTION_DATE TIMESTAMP_NTZ ,
    TRANSACTION_TYPE VARCHAR(50),
    AMOUNT DECIMAL(18, 2),
    CURRENCY_CODE CHAR(3),
    CONVERSION_RATE DECIMAL(18, 6) ,
    USD_AMOUNT DECIMAL(18, 2),
    CHANNEL VARCHAR(50),
    CREATED_DATE TIMESTAMP_NTZ ,
    PRIMARY KEY (TRANSACTION_SK)
)
USING DELTA
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact'   = 'true'
);

CREATE OR REPLACE TABLE FRAUD_DETECTION.FRAUD.ACCOUNT_DAILY_SNAPSHOT (
    SNAPSHOT_DATE DATE NOT NULL,
    ACCOUNT_SK BIGINT NOT NULL,
    OPENING_BALANCE DECIMAL(18, 2),
    CLOSING_BALANCE DECIMAL(18, 2),
    TOTAL_CREDITS DECIMAL(18, 2),
    TOTAL_DEBITS DECIMAL(18, 2),
    TRANSACTION_COUNT BIGINT,
    AVG_TRANSACTION_SIZE DECIMAL(18, 2),
    MAX_TRANSACTION_SIZE DECIMAL(18, 2),
    CREATED_DATE TIMESTAMP_NTZ ,
    PRIMARY KEY (SNAPSHOT_DATE, ACCOUNT_SK)
)
USING DELTA
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact'   = 'true'
);

CREATE OR REPLACE TABLE FRAUD_DETECTION.FRAUD.HIGH_RISK_COUNTRIES (
    COUNTRY_CODE CHAR(2) PRIMARY KEY,
    COUNTRY_NAME VARCHAR(100),
    RISK_LEVEL VARCHAR(20),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    UPDATED_DATE TIMESTAMP_NTZ
)
USING DELTA
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.feature.allowColumnDefaults' = 'supported',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact'   = 'true'
);

CREATE OR REPLACE TABLE FRAUD_DETECTION.FRAUD.CURRENCY_EXCHANGE_RATES (
    FROM_CURRENCY CHAR(3),
    TO_CURRENCY CHAR(3),
    RATE DECIMAL(18, 6),
    EFFECTIVE_DATE DATE,
    CREATED_DATE TIMESTAMP_NTZ ,
    PRIMARY KEY (FROM_CURRENCY, TO_CURRENCY, EFFECTIVE_DATE)
)
USING DELTA
TBLPROPERTIES (
  'delta.deletedFileRetentionDuration' = 'interval 7 days',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact'   = 'true'
);

-- =====================================================
-- PART 2: INSERT REFERENCE DATA
-- =====================================================
INSERT INTO FRAUD_DETECTION.FRAUD.HIGH_RISK_COUNTRIES VALUES
('SY','Syria','HIGH',TRUE,CURRENT_TIMESTAMP()),
('AF','Afghanistan','HIGH',TRUE,CURRENT_TIMESTAMP()),
('KP','North Korea','CRITICAL',TRUE,CURRENT_TIMESTAMP()),
('IR','Iran','HIGH',TRUE,CURRENT_TIMESTAMP()),
('VE','Venezuela','HIGH',TRUE,CURRENT_TIMESTAMP()),
('UA','Ukraine','MEDIUM',TRUE,CURRENT_TIMESTAMP());

INSERT INTO FRAUD_DETECTION.FRAUD.CURRENCY_EXCHANGE_RATES VALUES
('USD','USD',1.0,CURRENT_DATE(),CURRENT_TIMESTAMP()),
('EUR','USD',1.08,CURRENT_DATE(),CURRENT_TIMESTAMP()),
('GBP','USD',1.25,CURRENT_DATE(),CURRENT_TIMESTAMP());

-- =====================================================
-- PART 3: CUSTOMER DATA
-- =====================================================
INSERT INTO FRAUD_DETECTION.FRAUD.CUSTOMER_MASTER
(CUSTOMER_ID,CUSTOMER_NAME,TAX_ID,EMAIL,SEGMENT,COUNTRY,RISK_SCORE,ADDRESS_LINE1,CITY,STATE)
VALUES
('C001','Global Imports Inc','12-3456789','finance@globalimports.com','ENTERPRISE','US',25.5,'123 Trade Center','New York','NY'),
('C002','Digital Retail Co','98-7654321','accounts@digitalretail.com','MID_MARKET','CA',45.0,'456 Tech Blvd','Toronto','ON');

-- =====================================================
-- PART 4: ACCOUNT DATA
-- =====================================================
INSERT INTO FRAUD_DETECTION.FRAUD.ACCOUNT_MASTER
(ACCOUNT_NUMBER,CUSTOMER_SK,ACCOUNT_TYPE,CURRENCY_CODE,CURRENT_BALANCE,AVAILABLE_BALANCE)
SELECT
'ACC'||CUSTOMER_SK||'01',
CUSTOMER_SK,
'CHECKING',
'USD',
5000 + CUSTOMER_SK*1000,
4500 + CUSTOMER_SK*1000
FROM FRAUD_DETECTION.FRAUD.CUSTOMER_MASTER;

-- =====================================================
-- PART 5: MERCHANT DATA
-- =====================================================
INSERT INTO FRAUD_DETECTION.FRAUD.MERCHANT_MASTER
(MERCHANT_ID,MERCHANT_NAME,CATEGORY_CODE,RISK_LEVEL,COUNTRY)
VALUES
('M001','Amazon','ELECT','LOW','US'),
('M002','Walmart','RETA','LOW','US'),
('M013','Bitcoin Exchange','CRYPTO','HIGH','MT');

-- =====================================================
-- PART 6: TRANSACTION DATA
-- =====================================================
INSERT INTO FRAUD_DETECTION.FRAUD.TRANSACTION_FACT
(TRANSACTION_ID,ACCOUNT_SK,MERCHANT_SK,TRANSACTION_TYPE,AMOUNT,CURRENCY_CODE,CHANNEL)
SELECT
'TXN'||MONOTONICALLY_INCREASING_ID(),
a.ACCOUNT_SK,
m.MERCHANT_SK,
'PURCHASE',
FLOOR(10 + RAND() * (500 - 10 + 1)),
'USD',
'ONLINE'
FROM FRAUD_DETECTION.FRAUD.ACCOUNT_MASTER a
CROSS JOIN FRAUD_DETECTION.FRAUD.MERCHANT_MASTER m
LIMIT 500;

-- =====================================================
-- PART 7: VIEWS
-- =====================================================
CREATE OR REPLACE VIEW FRAUD_DETECTION.FRAUD.V_CUSTOMER_RISK_DASHBOARD AS
SELECT
cm.CUSTOMER_SK,
cm.CUSTOMER_NAME,
cm.RISK_SCORE,
COUNT(tf.TRANSACTION_ID) total_transactions,
AVG(tf.AMOUNT) avg_transaction_amount,
MAX(tf.AMOUNT) max_transaction_amount
FROM FRAUD_DETECTION.FRAUD.CUSTOMER_MASTER cm
LEFT JOIN FRAUD_DETECTION.FRAUD.ACCOUNT_MASTER am
ON cm.CUSTOMER_SK = am.CUSTOMER_SK
LEFT JOIN FRAUD_DETECTION.FRAUD.TRANSACTION_FACT tf
ON am.ACCOUNT_SK = tf.ACCOUNT_SK
GROUP BY cm.CUSTOMER_SK,cm.CUSTOMER_NAME,cm.RISK_SCORE;

-- =====================================================
-- PART 8: SNAPSHOT DATA
-- =====================================================
INSERT INTO FRAUD_DETECTION.FRAUD.ACCOUNT_DAILY_SNAPSHOT
(SNAPSHOT_DATE,ACCOUNT_SK,OPENING_BALANCE,CLOSING_BALANCE)
SELECT
CURRENT_DATE(),
ACCOUNT_SK,
CURRENT_BALANCE,
CURRENT_BALANCE + 100
FROM FRAUD_DETECTION.FRAUD.ACCOUNT_MASTER;

-- =====================================================
-- PART 9: VALIDATION
-- =====================================================
SELECT 'CUSTOMER_MASTER',COUNT(*) FROM FRAUD_DETECTION.FRAUD.CUSTOMER_MASTER
UNION ALL
SELECT 'ACCOUNT_MASTER',COUNT(*) FROM FRAUD_DETECTION.FRAUD.ACCOUNT_MASTER
UNION ALL
SELECT 'MERCHANT_MASTER',COUNT(*) FROM FRAUD_DETECTION.FRAUD.MERCHANT_MASTER
UNION ALL
SELECT 'TRANSACTION_FACT',COUNT(*) FROM FRAUD_DETECTION.FRAUD.TRANSACTION_FACT;

-- ============================================================
-- ENTERPRISE FRAUD ANALYTICS VIEW LAYER
-- Compatible with Snowflake
-- Schema : FRAUD_DETECTION.FRAUD
-- ============================================================
USE CATALOG FRAUD_DETECTION;

-- USE SCHEMA FRAUD;  -- (Databricks: qualify as USE SCHEMA <catalog>.FRAUD)

-- ============================================================
-- VIEW 1 : CUSTOMER 360 FINANCIAL PROFILE
-- ============================================================
CREATE OR REPLACE VIEW FRAUD_DETECTION.FRAUD.V_CUSTOMER_360_PROFILE AS
WITH account_stats AS
(
SELECT
    cm.CUSTOMER_SK,
    COUNT(DISTINCT am.ACCOUNT_SK) ACCOUNT_COUNT,
    SUM(am.CURRENT_BALANCE) TOTAL_BALANCE,
    AVG(am.CURRENT_BALANCE) AVG_BALANCE,
    MAX(am.CURRENT_BALANCE) MAX_BALANCE
FROM FRAUD_DETECTION.FRAUD.CUSTOMER_MASTER cm
LEFT JOIN FRAUD_DETECTION.FRAUD.ACCOUNT_MASTER am
ON cm.CUSTOMER_SK = am.CUSTOMER_SK
GROUP BY cm.CUSTOMER_SK
),
transaction_stats AS
(
SELECT
    am.CUSTOMER_SK,
    COUNT(tf.TRANSACTION_SK) TXN_COUNT,
    SUM(tf.AMOUNT) TOTAL_TXN_AMOUNT,
    AVG(tf.AMOUNT) AVG_TXN_AMOUNT,
    MAX(tf.AMOUNT) MAX_TXN
FROM FRAUD_DETECTION.FRAUD.ACCOUNT_MASTER am
JOIN FRAUD_DETECTION.FRAUD.TRANSACTION_FACT tf
ON am.ACCOUNT_SK = tf.ACCOUNT_SK
GROUP BY am.CUSTOMER_SK
)
SELECT
cm.CUSTOMER_SK,
cm.CUSTOMER_NAME,
cm.SEGMENT,
cm.COUNTRY,
cm.RISK_SCORE,
a.ACCOUNT_COUNT,
a.TOTAL_BALANCE,
a.AVG_BALANCE,
t.TXN_COUNT,
t.TOTAL_TXN_AMOUNT,
t.AVG_TXN_AMOUNT,
t.MAX_TXN
FROM FRAUD_DETECTION.FRAUD.CUSTOMER_MASTER cm
LEFT JOIN account_stats a
ON cm.CUSTOMER_SK = a.CUSTOMER_SK
LEFT JOIN transaction_stats t
ON cm.CUSTOMER_SK = t.CUSTOMER_SK
;

-- ============================================================
-- VIEW 2 : MERCHANT FRAUD RISK ANALYTICS
-- ============================================================
CREATE OR REPLACE VIEW FRAUD_DETECTION.FRAUD.V_MERCHANT_FRAUD_ANALYTICS AS
WITH merchant_txn AS
(
SELECT
mm.MERCHANT_SK,
mm.MERCHANT_NAME,
mm.CATEGORY_CODE,
mm.RISK_LEVEL,
COUNT(tf.TRANSACTION_SK) TXN_COUNT,
SUM(tf.AMOUNT) TOTAL_AMOUNT,
AVG(tf.AMOUNT) AVG_AMOUNT,
MAX(tf.AMOUNT) MAX_TXN
FROM FRAUD_DETECTION.FRAUD.MERCHANT_MASTER mm
LEFT JOIN FRAUD_DETECTION.FRAUD.TRANSACTION_FACT tf
ON mm.MERCHANT_SK = tf.MERCHANT_SK
GROUP BY
mm.MERCHANT_SK,
mm.MERCHANT_NAME,
mm.CATEGORY_CODE,
mm.RISK_LEVEL
)
SELECT
*,
CASE
WHEN TOTAL_AMOUNT > 100000 THEN 'CRITICAL'
WHEN TOTAL_AMOUNT > 50000 THEN 'HIGH'
WHEN TOTAL_AMOUNT > 10000 THEN 'MEDIUM'
ELSE 'LOW'
END AS MERCHANT_ACTIVITY_RISK
FROM merchant_txn
;

-- ============================================================
-- VIEW 3 : TRANSACTION ANOMALY DETECTION
-- ============================================================
CREATE OR REPLACE VIEW FRAUD_DETECTION.FRAUD.V_TRANSACTION_ANOMALY_DETECTION AS
WITH txn_window AS
(
SELECT
tf.TRANSACTION_SK,
tf.TRANSACTION_ID,
tf.ACCOUNT_SK,
tf.MERCHANT_SK,
tf.AMOUNT,
tf.TRANSACTION_DATE,
AVG(tf.AMOUNT) OVER (PARTITION BY tf.ACCOUNT_SK) AVG_ACCOUNT_TXN,
STDDEV(tf.AMOUNT) OVER (PARTITION BY tf.ACCOUNT_SK) STD_ACCOUNT_TXN
FROM FRAUD_DETECTION.FRAUD.TRANSACTION_FACT tf
),
scored_txn AS
(
SELECT
*,
CASE
WHEN AMOUNT > AVG_ACCOUNT_TXN + (3 * STD_ACCOUNT_TXN)
THEN 'ANOMALY'
ELSE 'NORMAL'
END ANOMALY_FLAG
FROM txn_window
)
SELECT
st.TRANSACTION_SK,
st.TRANSACTION_ID,
st.ACCOUNT_SK,
st.AMOUNT,
st.ANOMALY_FLAG,
cm.CUSTOMER_NAME,
mm.MERCHANT_NAME
FROM scored_txn st
JOIN FRAUD_DETECTION.FRAUD.ACCOUNT_MASTER am
ON st.ACCOUNT_SK = am.ACCOUNT_SK
JOIN FRAUD_DETECTION.FRAUD.CUSTOMER_MASTER cm
ON am.CUSTOMER_SK = cm.CUSTOMER_SK
JOIN FRAUD_DETECTION.FRAUD.MERCHANT_MASTER mm
ON st.MERCHANT_SK = mm.MERCHANT_SK
;

-- ============================================================
-- VIEW 4 : ACCOUNT BEHAVIOR TREND ANALYTICS
-- ============================================================
CREATE OR REPLACE VIEW FRAUD_DETECTION.FRAUD.V_ACCOUNT_BEHAVIOR_TRENDS AS
WITH daily_txn AS
(
SELECT
am.ACCOUNT_SK,
DATE_TRUNC('DAY',tf.TRANSACTION_DATE) TXN_DAY,
COUNT(*) TXN_COUNT,
SUM(tf.AMOUNT) DAILY_TOTAL
FROM FRAUD_DETECTION.FRAUD.ACCOUNT_MASTER am
JOIN FRAUD_DETECTION.FRAUD.TRANSACTION_FACT tf
ON am.ACCOUNT_SK = tf.ACCOUNT_SK
GROUP BY
am.ACCOUNT_SK,
DATE_TRUNC('DAY',tf.TRANSACTION_DATE)
),
trend_calc AS
(
SELECT
ACCOUNT_SK,
TXN_DAY,
TXN_COUNT,
DAILY_TOTAL,
AVG(DAILY_TOTAL) OVER
(
PARTITION BY ACCOUNT_SK
ORDER BY TXN_DAY
ROWS BETWEEN 7 PRECEDING AND CURRENT ROW
) MOVING_AVG_7D
FROM daily_txn
)
SELECT
*
FROM trend_calc
;

-- ============================================================
-- VIEW 5 : ENTERPRISE FRAUD SCORING ENGINE
-- ============================================================
CREATE OR REPLACE VIEW FRAUD_DETECTION.FRAUD.V_ENTERPRISE_FRAUD_SCORE AS
WITH base_txn AS
(
SELECT
tf.TRANSACTION_SK,
tf.ACCOUNT_SK,
tf.MERCHANT_SK,
tf.AMOUNT,
tf.TRANSACTION_DATE,
am.CUSTOMER_SK
FROM FRAUD_DETECTION.FRAUD.TRANSACTION_FACT tf
JOIN FRAUD_DETECTION.FRAUD.ACCOUNT_MASTER am
ON tf.ACCOUNT_SK = am.ACCOUNT_SK
),
customer_risk AS
(
SELECT
CUSTOMER_SK,
RISK_SCORE
FROM FRAUD_DETECTION.FRAUD.CUSTOMER_MASTER
),
merchant_risk AS
(
SELECT
MERCHANT_SK,
CASE
WHEN RISK_LEVEL = 'HIGH' THEN 80
WHEN RISK_LEVEL = 'MEDIUM' THEN 50
ELSE 20
END MERCHANT_RISK_SCORE
FROM FRAUD_DETECTION.FRAUD.MERCHANT_MASTER
),
fraud_score_calc AS
(
SELECT
b.TRANSACTION_SK,
b.ACCOUNT_SK,
b.AMOUNT,
cr.RISK_SCORE CUSTOMER_RISK,
mr.MERCHANT_RISK_SCORE,
(b.AMOUNT/100) + cr.RISK_SCORE + mr.MERCHANT_RISK_SCORE FRAUD_SCORE
FROM base_txn b
LEFT JOIN customer_risk cr
ON b.CUSTOMER_SK = cr.CUSTOMER_SK
LEFT JOIN merchant_risk mr
ON b.MERCHANT_SK = mr.MERCHANT_SK
)
SELECT
*,
CASE
WHEN FRAUD_SCORE > 150 THEN 'CRITICAL'
WHEN FRAUD_SCORE > 100 THEN 'HIGH'
WHEN FRAUD_SCORE > 50 THEN 'MEDIUM'
ELSE 'LOW'
END FRAUD_ALERT_LEVEL
FROM fraud_score_calc
;